spring.application.name=spring-boot
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
spring.datasource.username=app_user
spring.datasource.password=app_pass123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.properties.hibernate.format_sql=true
spring.thymeleaf.cache=false

app.security.jwt.secret=VjNWaGNtVnlJR0YwS1hSb2FYTWdZWEJoYm5ScGJtY2daR2xsSUdsdVp5QnViM1FnY21WaGJHeDVMZz09
app.security.jwt.expiration-ms=3600000
app.security.seed.enabled=true